version: "3.9"

services:
  db:
    image: postgres:13.1-alpine
    env_file: .env-db
    volumes:
    - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
    - db
    env_file: .env-web
    